### ISSUE TITLE
[Bug] After /mute command and reload cannot access any channel

### ISSUE THREAD

**Issue by geweald** [GetStream/stream-chat-flutter#1046]
### Which packages are you using?

stream_chat_flutter, stream_chat_persistance

### On what platforms did you experience the issue?

iOS, Android, Web

### What version are you using?

Latest

### What happened?
After muting an user and reloading the app:

In `stream_chat-3.5.1/lib/src/core/models/mute.g.dart` (this exception cannot be caught outside of the library)

![image](https://user-images.githubusercontent.com/16155640/160817444-1e60a77b-2279-4fd8-a3c7-704dd5bca474.png)

### Steps to reproduce

```bash
1. Open channel
2. Use `/mute @user` (mute an user)
3. Refresh/restart the app, the channel or any other channel will never load because of the exception when fetching user data probably
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by geiszla** [comment]
We have the same issue for some users. They get the following error when we call `streamChatClient.connectUser(...)`.

```
I/flutter (28801): 2022-03-30 13:59:03.287894 ⚠️ 🔌 Error parsing an event: NoSuchMethodError: The method 'forEach' was called on null.
I/flutter (28801): Receiver: nul
I/flutter (28801): Tried calling: forEach(Closure: (dynamic, dynamic) => void)
I/flutter (28801): 2022-03-30 13:59:03.292658 ⚠️ 🔌 Stack trace: #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
I/flutter (28801): #1      new LinkedHashMap.from (dart:collection/linked_hash_map.dart:186:11)
I/flutter (28801): #2      Serializer.moveToExtraDataFromRoot
package:stream_chat/…/util/serializer.dart:15
I/flutter (28801): #3      new ChannelModel.fromJson
package:stream_chat/…/models/channel_model.dart:41
I/flutter (28801): #4      _$MuteFromJson
package:stream_chat/…/models/mute.g.dart:11
I/flutter (28801): #5      new Mute.fromJson
package:stream_chat/…/models/mute.dart:20
I/flutter (28801): #6      _$OwnUserFromJson.<anonymous closure>
package:stream_chat/…/models/own_user.g.dart:15
I/flutter (28801): #7      MappedListIterable.elementAt (dart:_internal/iterable.dart:413:31)
I/flutter (28801): #8      ListIterator.moveNext (dart:_internal/iterable.dart:342:26)

```
