### ISSUE TITLE
Unsupported operation: Cannot remove from an unmodifiable list

### ISSUE THREAD

**Issue by Abacaxi-Nelson** [GetStream/stream-chat-flutter#1054]
### Which packages are you using?

stream_chat, stream_chat_flutter

### On what platforms did you experience the issue?

iOS

### What version are you using?

Last version

### What happened?

Usually, on first launch, i get following error 

lutter: ----------------FIREBASE CRASHLYTICS----------------
flutter: Unsupported operation: Cannot remove from an unmodifiable list
flutter:
#0      UnmodifiableListMixin.removeWhere (dart:_internal[/list.dart:139:5]())
#1      ChannelClientState._listenMemberRemoved.<anonymous closure>
package:stream_chat/…/client/channel.dart:1592
#2      _rootRunUnary (dart:async[/zone.dart:1434:47]())
#3      _CustomZone.runUnary (dart:async[/zone.dart:1335:19]())
#4      _CustomZone.runUnaryGuarded (dart:async[/zone.dart:1244:7]())
#5      _BufferingStreamSubscription._sendData (dart:async[/stream_impl.dart:341:11]())
#6      _BufferingStreamSubscription._add (dart:async[/stream_impl.dart:271:7]())
#7      _ForwardingStreamSubscription._add (dart:async[/stream_pipe.dart:123:11]())
#8      _WhereStream._handleData (dart:async[/stream_pipe.dart:195:12]())
#9      _rootRunUnary (dart:async[/zone.dart:1434:47]())
#10     _CustomZone.runUnary (dart:async[/zone.dart:1335:19]())
#11     _CustomZone.runUnaryGuarded (dart:async[/zone.dart:1244:7]())
#12     _BufferingStreamSubscription._sendData (dart:async[/stream_impl.dart:341:11]())
#13     _BufferingStreamSubscription._add (dart:<…>
flutter: ----------------------------------------------------

Code is this one 

```
in channel.dart l.1592 
void _listenMemberRemoved() {
    _subscriptions.add(_channel.on(EventType.memberRemoved).listen((Event e) {
      final user = e.user;
      updateChannelState(channelState.copyWith(
        members: List.from(
          channelState.members..removeWhere((m) => m.userId == user!.id),
        ),
        read: channelState.read..removeWhere((r) => r.user.id == user!.id), // THIS LINE
      ));
    }));
  }
```

### Steps to reproduce

```bash
Run the app, load chats
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Abacaxi-Nelson** [comment]
thanks @imtoori
