### ISSUE TITLE
Error: Bad state: Future already completed

### ISSUE THREAD

**Issue by tanjunior** [GetStream/stream-chat-flutter#1145]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

Web

### What version are you using?

stream_chat_flutter: ^3.6.1

### What happened?

ChannelListView causing errors on Web.

Breaks at `dio-4.0.6\lib\src\adapters\browser_adapter.dart` when ran in debug mode.

Runs fine on android.

### Steps to reproduce

```bash
Follow https://www.youtube.com/watch?v=pO_MOJRqYlk
```

### Relevant log output

```shell
Error: Bad state: Future already completed
    at Object.throw_ [as throw] (http://localhost:50788/dart_sdk.js:5067:11)
    at _AsyncCompleter.new.completeError (http://localhost:50788/dart_sdk.js:35195:51)
at http://localhost:50788/packages/dio/src/interceptors/log.dart.lib.js:651:25
    at _RootZone.runUnary (http://localhost:50788/dart_sdk.js:40441:59)
    at _FutureListener.then.handleValue (http://localhost:50788/dart_sdk.js:35363:29)
    at handleValueCallback (http://localhost:50788/dart_sdk.js:35931:49)
    at Function._propagateToListeners (http://localhost:50788/dart_sdk.js:35969:17)
    at _Future.new.[_complete] (http://localhost:50788/dart_sdk.js:35809:25)
    at http://localhost:50788/dart_sdk.js:34915:30
    at internalCallback (http://localhost:50788/dart_sdk.js:26619:11)
```

### Flutter doctor output

```shell
[√] Flutter (Channel stable, 2.10.5, on Microsoft Windows [Version 10.0.19043.1645], locale en-SG)
    • Flutter version 2.10.5 at E:\dev\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (4 weeks ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
    • Android SDK at E:\dev\Android\SDK
    • Platform android-31, build-tools 33.0.0-rc1
    • Java binary at: E:\dev\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31624.102
    • Windows 10 SDK version 10.0.17763.0
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[√] Android Studio (version 2021.1)
    • Android Studio at E:\dev\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19043.1645]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 100.0.4896.127
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 100.0.1185.50

[√] HTTP Host Availability
    • All required HTTP hosts are available
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tanjunior** [comment]
[dio#1454](https://github.com/flutterchina/dio/issues/1454) seems like it's an issue with 4.0.6 of dio. Possible downgrade to 4.0.5?

**Comment by tanjunior** [comment]
Happens when the page is rendering `UserListView` and `ChannelListView`

**Comment by imtoori** [comment]
hey @tanjunior you can try adding 
```yaml
dependency_overrides:
  dio: 4.0.4
```

to your pubspec file

**Comment by tanjunior** [comment]
> hey @tanjunior you can try adding
> 
> ```yaml
> dependency_overrides:
>   dio: 4.0.4
> ```
> 
> to your pubspec file

Thank you!

**Comment by tanjunior** [comment]
Update on 2023. I noticed that streamchat has updated their dio dependencies to 5.1.1. So I tried removing dependency override of 4.0.4 but it seems like the issue still persist.
