### ISSUE TITLE
SqliteException(1): while preparing statement, no such column: messages.state, SQL logic error (code 1)

### ISSUE THREAD

**Issue by Mounix99** [GetStream/stream-chat-flutter#1683]
### Which packages are you using?

stream_chat_flutter, stream_chat_persistance, stream_chat_localizations

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

  stream_chat_flutter: ^6.7.0
  stream_chat_localizations: ^5.7.0
  stream_chat_persistence: ^6.6.0

### What happened?

I start receiving this error on production app. some users can't even load list of conversation. 

### Steps to reproduce

```bash
1. try to load conversations
```

### Relevant log output

```shell
flutter: ----------------FIREBASE CRASHLYTICS----------------
flutter: SqliteException(1): while preparing statement, no such column: messages.state, SQL logic error (code 1)
  Causing statement: SELECT "messages"."id" AS "messages.id", "messages"."message_text" AS "messages.message_text", "messages"."attachments" AS "messages.attachments", "messages"."state" AS "messages.state", "messages"."type" AS "messages.type", "messages"."mentioned_users" AS "messages.mentioned_users", "messages"."reaction_counts" AS "messages.reaction_counts", "messages"."reaction_scores" AS "messages.reaction_scores", "messages"."parent_id" AS "messages.parent_id", "messages"."quoted_message_id" AS "messages.quoted_message_id", "messages"."reply_count" AS "messages.reply_count", "messages"."show_in_channel" AS "messages.show_in_channel", "messages"."shadowed" AS "messages.shadowed", "messages"."command" AS "messages.command", "messages"."local_created_at" AS "messages.local_created_at", "messages"."remote_created_at" AS "messages.remote_created_at", "messages"."local_updated_at" <…>
flutter: 
#0      throwException (package:sqlite3/src/implementation/exception.dart:75:3)
#1      DatabaseImplementation._prepareInternal (package:sqlite3/src/implementation/database.dart:300:9)
#2      DatabaseImplementation.prepare (package:sqlite3/src/implementation/database.dart:359:19)
#3      FfiDatabaseImplementation.prepare (package:sqlite3/src/ffi/implementation.dart:111:18)
#4      Sqlite3Delegate._getPreparedStatement (package:drift/src/sqlite3/database.dart:173:29)
#5      Sqlite3Delegate.runSelect (package:drift/src/sqlite3/database.dart:151:18)
#6      _BaseExecutor.runSelect.<anonymous closure> (package:drift/src/runtime/executor/helpers/engines.dart:77:19)
#7      _BaseExecutor._synchronized (package:drift/src/runtime/executor/helpers/engines.dart:61:20)
#8      _BaseExecutor.runSelect (package:drift/src/runtime/executor/helpers/engines.dart:74:26)
#9      LazyDatabase.runSelect (package:drift/src/utils/lazy_database.dart:83:22)
#10     JoinedSelectStatement._getRaw.<anonymous c<…>
flutter: ----------------------------------------------------
flutter: ----------------FIREBASE CRASHLYTICS----------------
flutter: SqliteException(1): while preparing statement, table messages has no column named state, SQL logic error (code 1)
  Causing statement: INSERT INTO "messages" ("id", "message_text", "attachments", "state", "type", "mentioned_users", "reaction_counts", "reaction_scores", "reply_count", "shadowed", "remote_created_at", "remote_updated_at", "user_id", "pinned", "channel_cid", "extra_data") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ON CONFLICT("id") DO UPDATE SET "id" = ?, "message_text" = ?, "attachments" = ?, "state" = ?, "type" = ?, "mentioned_users" = ?, "reaction_counts" = ?, "reaction_scores" = ?, "reply_count" = ?, "shadowed" = ?, "remote_created_at" = ?, "remote_updated_at" = ?, "user_id" = ?, "pinned" = ?, "channel_cid" = ?, "extra_data" = ?
flutter: 
#0      throwException (package:sqlite3/src/implementation/exception.dart:75:3)
#1      DatabaseImplementation._prepareInternal (package:sqlite3/src/implementation/database.dart:300:9)
#2      DatabaseImplementation.prepare (package:sqlite3/src/implementation/database.dart:359:19)
#3      FfiDatabaseImplementation.prepare (package:sqlite3/src/ffi/implementation.dart:111:18)
#4      Sqlite3Delegate.runBatchSync (package:drift/src/sqlite3/database.dart:118:31)
#5      _NativeDelegate.runBatched.<anonymous closure> (package:drift/native.dart:281:30)
#6      new Future.sync (dart:async/future.dart:305:31)
#7      _NativeDelegate.runBatched (package:drift/native.dart:281:19)
#8      _BaseExecutor.runBatched.<anonymous closure> (package:drift/src/runtime/executor/helpers/engines.dart:127:19)
#9      _BaseExecutor._synchronized (package:drift/src/runtime/executor/helpers/engines.dart:61:20)
#10     _BaseExecutor.runBatched (package:drift/src/runtime/executor/helpers/engines.dart:121:12)
#11 <…>
flutter: ----------------------------------------------------
```

### Flutter doctor output

```shell
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.4.1 22F770820d darwin-arm64, locale en-UA)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xsahil03x** [comment]
@Mounix99 adding a fix, can you meanwhile try clearing data and start the app again. Picking this up on priority.

**Comment by xsahil03x** [comment]
Hey @Mounix99,  adding a quick fix. Meanwhile can you try clearing the app data? Taking this on priority.

**Comment by Mounix99** [comment]
@xsahil03x App re-installation helps, but not for all users. Thanks for the quick answer. About the fix, suppose it will not require package update or it will?

**Comment by xsahil03x** [comment]
@Mounix99 in order to update the schema yes, you will need to use the latest release which i am gonna make soon. But a pub upgrade will also work.

**Comment by Mounix99** [comment]
Already got it from PR, thanks. Wil wait

**Comment by Mounix99** [comment]
@xsahil03x  Am I understanding right?  stream_chat_flutter 6.8.0 included this changes ?

**Comment by xsahil03x** [comment]
@Mounix99 This fix is actually in the `stream_chat_persistence: 6.7.0`. But I will advice to also update `stream_chat_flutter` along with it.
https://pub.dev/packages/stream_chat_persistence/changelog#670

**Comment by Mounix99** [comment]
Thanks
