### ISSUE TITLE
SqliteException(5): while executing statement, database is locked - V6.8.0

### ISSUE THREAD

**Issue by hajajmaor** [GetStream/stream-chat-flutter#1760]
Happening on debug

  pubspec.yaml

```yaml
  stream_chat_flutter_core: ^6.8.0
  stream_chat_persistence: ^6.8.0
```

<details>
  <summary> Partial log </summary>

```
E/flutter (29575): #6      DatabaseConnectionUser.transaction.<anonymous closure>.<anonymous closure>
connection_user.dart:467
E/flutter (29575): <asynchronous suspension>
E/flutter (29575): #7      DatabaseConnectionUser.transaction
connection_user.dart:460
E/flutter (29575): <asynchronous suspension>
E/flutter (29575):
E/flutter (29575): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: SqliteException(5): while executing statement, database is locked, database is locked (code 5)
E/flutter (29575):   Causing statement: DELETE FROM "members" WHERE "channel_cid" IN (?);, parameters: messaging:XXXXXXX
E/flutter (29575): #0      DriftCommunication.request
communication.dart:113
E/flutter (29575): #1      _BaseExecutor.runBatched
client_impl.dart:80
E/flutter (29575): #2      Batch._runWith
batch.dart:215
E/flutter (29575): #3      Batch._commit
batch.dart:207
E/flutter (29575): <asynchronous suspension>
E/flutter (29575): #4      Future.wait.<anonymous closure> (dart:async/future.dart:525:21)
E/flutter (29575): <asynchronous suspension>
E/flutter (29575): #5      ChatPersistenceClient.updateChannelStates
chat_persistence_client.dart:297
E/flutter (29575): <asynchronous suspension>
E/flutter (29575): #6      DatabaseConnectionUser.transaction.<anonymous closure>.<anonymous closure>
connection_user.dart:467
E/flutter (29575): <asynchronous suspension>
E/flutter (29575): #7      DatabaseConnectionUser.transaction
connection_user.dart:460
E/flutter (29575): <asynchronous suspension>
E/flutter (29575):
E/flutter (29575): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: SqliteException(5): while executing statement, database is locked, database is locked (code 5)
E/flutter (29575):   Causing statement: DELETE FROM "members" WHERE "channel_cid" IN (?);, parameters: messaging:XXXXXXX
E/flutter (29575): #0      DriftCommunication.request
communication.dart:113
E/flutter (29575): #1      _BaseExecutor.runBatched
client_impl.dart:80
E/flutter (29575): #2      Batch._runWith
batch.dart:215
E/flutter (29575): #3      Batch._commit
batch.dart:207
E/flutter (29575): <asynchronous suspension>
E/flutter (29575): #4      Future.wait.<anonymous closure> (dart:async/future.dart:525:21)
E/flutter (29575): <asynchronous suspension>
E/flutter (29575): #5      ChatPersistenceClient.updateChannelStates
chat_persistence_client.dart:297
E/flutter (29575): <asynchronous suspension>
E/flutter (29575): #6      DatabaseConnectionUser.transaction.<anonymous closure>.<anonymous closure>
connection_user.dart:467
E/flutter (29575): <asynchronous suspension>
E/flutter (29575): #7      DatabaseConnectionUser.transaction
connection_user.dart:460
E/flutter (29575): <asynchronous suspension>
E/flutter (29575):
E/flutter (29575): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: SqliteException(5): while executing statement, database is locked, database is locked (code 5)
E/flutter (29575):   Causing statement: DELETE FROM "members" WHERE "channel_cid" 
```

</details>

**Comment by esarbanis** [comment]
Hi @hajajmaor thank you for opening this issue with us.
 
This usually happens when the database is opened twice, or a previous transaction was interrupted before committing/rollbacking. You should check your code to identify if you call the persistence client in a weird way (either multiple times or not waiting for actions to finish.
