### ISSUE TITLE
Exception caught by image resource service: Invalid argument(s): No host specified in URI

### ISSUE THREAD

**Issue by Ssiswent** [GetStream/stream-chat-flutter#1906]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS

### What version are you using?

```dart
stream_chat_flutter_core: 7.2.0-hotfix.1
stream_chat_flutter: 7.2.0-hotfix.1
stream_chat_persistence: 7.2.0-hotfix.1
stream_chat_localizations: 7.2.0-hotfix.1
```

### What happened?

![image](https://github.com/GetStream/stream-chat-flutter/assets/37449310/78876fc0-44f4-4755-acc7-80be22a14b51)

### Steps to reproduce

```bash
1. Open channel list page
2. Go to one channel which contains images or not
3. Watch the console, there are some errors
```

### Supporting info to reproduce

This issue only produces on iOS with the same code.

### Relevant log output

```shell
════════ Exception caught by image resource service ════════════════════════════
The following ArgumentError was thrown resolving an image codec:
Invalid argument(s): No host specified in URI

When the exception was thrown, this was the stack:
#0      _HttpClient._openUrl (dart:_http/http_impl.dart:2752:9)
http_impl.dart:2752
#1      _HttpClient.openUrl (dart:_http/http_impl.dart:2623:7)
http_impl.dart:2623
#2      IOClient.send (package:http/src/io_client.dart:117:38)
io_client.dart:117
#3      HttpFileService.get (package:flutter_cache_manager/src/web/file_service.dart:37:44)
file_service.dart:37
#4      WebHelper._download (package:flutter_cache_manager/src/web/web_helper.dart:115:24)
web_helper.dart:115
#5      WebHelper._updateFile (package:flutter_cache_manager/src/web/web_helper.dart:97:28)
web_helper.dart:97
<asynchronous suspension>
#6      WebHelper._downloadOrAddToQueue (package:flutter_cache_manager/src/web/web_helper.dart:65:7)
web_helper.dart:65
<asynchronous suspension>

Image provider: CachedNetworkImageProvider("", scale: 1.0) 
 Image key: CachedNetworkImageProvider("", scale: 1.0): CachedNetworkImageProvider("", scale: 1.0)
════════════════════════════════════════════════════════════════════════════════
```
```


### Flutter analyze output

_No response_

### Flutter doctor output

```shell
[✓] Flutter (Channel stable, 3.19.5, on macOS 14.4.1 23E224 darwin-arm64, locale en-CN)
    • Flutter version 3.19.5 on channel stable at /Users/ssiswent/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 300451adae (4 weeks ago), 2024-03-27 21:54:07 -0500
    • Engine revision e76c956498
    • Dart version 3.3.3
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/ssiswent/Library/Android/sdk
    • Platform android-34, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio Preview.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.17-11446219)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version unknown)
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.17-11446219)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 73.0.4
    • Dart plugin version 231.8109.91

[✓] IntelliJ IDEA Ultimate Edition (version EAP IU-241.14494.17)
    • IntelliJ at /Applications/IntelliJ IDEA 2024.1 EAP.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.87.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] VS Code (version 1.89.0-insider)
    • VS Code at /Applications/Visual Studio Code - Insiders.app/Contents
    • Flutter extension version 3.86.0

[✓] Connected device (4 available)
    • Flamingo's 15 Pro (mobile) • 00008130-0001716436C0001C • ios            • iOS 17.4 21E5200d
    • Selina’s iPhone (mobile)   • 00008101-00084CC40A68001E • ios            • iOS 17.4.1 21E236
    • macOS (desktop)            • macos                     • darwin-arm64   • macOS 14.4.1 23E224 darwin-arm64
    • Chrome (web)               • chrome                    • web-javascript • Google Chrome 124.0.6367.62

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Jonny1987** [comment]
I am having the same issue
