### ISSUE TITLE
Native Media Loading Crash

### ISSUE THREAD

**Issue by searchy2** [GetStream/stream-chat-flutter#306]
**Describe the bug**
In the demo app, scrolling up in the chat causes the app to crash every time with the following error.
<summary>Error Logs</summary>
<details>

```
2021-03-02 17:26:21.802 2034-2060/? E/PackageManager: Optimistic bind failed.
    java.util.concurrent.TimeoutException: [Optimistic Bind] Didn't bind to resolver in time!
        at com.android.server.pm.InstantAppResolverConnection.waitForBindLocked(InstantAppResolverConnection.java:161)
        at com.android.server.pm.InstantAppResolverConnection.bind(InstantAppResolverConnection.java:226)
        at com.android.server.pm.InstantAppResolverConnection.lambda$optimisticBind$0$InstantAppResolverConnection(InstantAppResolverConnection.java:256)
        at com.android.server.pm.-$$Lambda$InstantAppResolverConnection$D-JKXi4qrYjnPQMOwj8UtfZenps.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)
2021-03-02 17:26:21.920 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.923 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.924 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.926 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.926 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.928 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.928 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.928 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.930 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.931 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.932 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.933 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.934 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.936 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.936 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.936 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.937 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.937 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.937 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.937 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.938 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.938 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.938 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.938 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.938 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.938 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.939 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.939 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.939 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.939 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.939 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.939 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.940 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.940 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.940 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.940 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.940 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.940 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.941 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.941 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.941 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.941 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.942 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.942 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.942 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.942 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.942 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.943 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.943 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.943 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.943 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.943 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.943 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.944 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.945 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.945 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.946 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.948 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.948 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.948 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.948 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.949 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.949 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.949 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.949 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.950 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.950 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.950 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.950 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.950 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.951 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.951 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.951 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.951 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.951 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.952 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.955 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.959 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.961 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.963 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.965 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.966 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:21.968 2034-2060/? E/memtrack: Couldn't load memtrack module
2021-03-02 17:26:22.152 8123-8123/? E/ocess.gservice: Not starting debugger since process cannot load the jdwp agent.
2021-03-02 17:26:22.189 1805-2554/? E/SurfaceFlinger: ro.sf.lcd_density must be defined as a build property
2021-03-02 17:26:22.192 1805-2554/? E/SurfaceFlinger: ro.sf.lcd_density must be defined as a build property
2021-03-02 17:26:22.221 1791-2347/? E/GnssHAL_GnssInterface: gnssSvStatusCb: a: input svInfo.flags is 8
2021-03-02 17:26:22.221 1791-2347/? E/GnssHAL_GnssInterface: gnssSvStatusCb: b: input svInfo.flags is 8
2021-03-02 17:26:22.459 8167-8167/? E/earchbox:searc: Not starting debugger since process cannot load the jdwp agent.
2021-03-02 17:26:22.915 8213-8213/? E/.apps.messagin: Not starting debugger since process cannot load the jdwp agent.
2021-03-02 17:26:23.002 8050-8239/? E/ActivityThread: Failed to find provider info for instantapp-dev-manager
2021-03-02 17:26:23.195 8065-8065/? E/WellbeingModel: Failed to register content observer for content://com.google.android.apps.wellbeing.api/actions: java.lang.SecurityException: Failed to find provider com.google.android.apps.wellbeing.api for user 0; expected to find a valid ContentProvider for this authority
2021-03-02 17:26:23.197 8065-8065/? E/libprocessgroup: set_timerslack_ns write failed: Operation not permitted
2021-03-02 17:26:23.204 8059-8059/? E/CarrierServices: [2] bas.G: Cannot access P-CSCF address, RCS configuration is null!
2021-03-02 17:26:23.204 8059-8059/? E/CarrierServices: [2] bas.A: Cannot access P-CSCF port, IMS configuration is null!
2021-03-02 17:26:23.221 1791-2347/? E/GnssHAL_GnssInterface: gnssSvStatusCb: a: input svInfo.flags is 8
2021-03-02 17:26:23.221 1791-2347/? E/GnssHAL_GnssInterface: gnssSvStatusCb: b: input svInfo.flags is 8
2021-03-02 17:26:23.322 8259-8259/? E/e.process.gapp: Not starting debugger since process cannot load the jdwp agent.
2021-03-02 17:26:23.322 8167-8167/? E/OverlaySController: Calling with an invalid UID, the interface will not work
2021-03-02 17:26:23.458 8065-8251/? E/ActivityThread: Failed to find provider info for com.google.android.apps.wellbeing.api
2021-03-02 17:26:23.504 8050-8250/? E/BluetoothAdapter: Bluetooth binder is null
2021-03-02 17:26:23.648 1805-2554/? E/SurfaceFlinger: ro.sf.lcd_density must be defined as a build property
2021-03-02 17:26:23.648 1805-2554/? E/SurfaceFlinger: ro.sf.lcd_density must be defined as a build property
2021-03-02 17:26:23.705 8059-8059/? E/CarrierServices: [2] bas.G: Cannot access P-CSCF address, RCS configuration is null!
2021-03-02 17:26:23.706 8059-8059/? E/CarrierServices: [2] bas.z: Cannot access P-CSCF address, IMS configuration is null!
2021-03-02 17:26:23.732 8065-8065/? E/libprocessgroup: set_timerslack_ns write failed: Operation not permitted
2021-03-02 17:26:23.735 8059-8059/? E/CarrierServices: [2] bas.G: Cannot access P-CSCF address, RCS configuration is null!
2021-03-02 17:26:23.736 8059-8059/? E/CarrierServices: [2] bas.A: Cannot access P-CSCF port, IMS configuration is null!
2021-03-02 17:26:23.736 8059-8059/? E/CarrierServices: [2] bas.G: Cannot access P-CSCF address, RCS configuration is null!
2021-03-02 17:26:23.737 8059-8059/? E/CarrierServices: [2] bas.z: Cannot access P-CSCF address, IMS configuration is null!
2021-03-02 17:26:23.763 8328-8328/? E/gle.android.gm: Not starting debugger since process cannot load the jdwp agent.
2021-03-02 17:26:23.943 8370-8370/? E/id.partnersetu: Not starting debugger since process cannot load the jdwp agent.
2021-03-02 17:26:24.222 1791-2347/? E/GnssHAL_GnssInterface: gnssSvStatusCb: a: input svInfo.flags is 8
2021-03-02 17:26:24.222 1791-2347/? E/GnssHAL_GnssInterface: gnssSvStatusCb: b: input svInfo.flags is 8
2021-03-02 17:26:24.324 8213-8238/? E/BugleRcsEngine: [3472] odm.getFile: File not found.: /data/user/0/com.google.android.apps.messaging/files/httpft_pending: open failed: ENOENT (No such file or directory)
    	libcore.io.IoBridge.open(IoBridge.java:496)
    	java.io.FileInputStream.<init>(FileInputStream.java:159)
    	android.app.ContextImpl.openFileInput(ContextImpl.java:600)
    	android.content.ContextWrapper.openFileInput(ContextWrapper.java:206)
    	odm.getFile(SourceFile:51)
    	odm.buildFiles(SourceFile:7)
    	com.google.android.apps.messaging.rcsmigration.RcsStateProvider.buildRcsState(SourceFile:63)
    	com.google.android.apps.messaging.rcsmigration.RcsStateProvider.getRcsState(SourceFile:6)
    	com.google.android.ims.rcsmigration.IRcsStateProvider$Stub.dispatchTransaction(SourceFile:6)
    	com.google.android.aidl.BaseStub.onTransact(SourceFile:11)
    	android.os.Binder.execTransactInternal(Binder.java:1021)
    	android.os.Binder.execTransact(Binder.java:994)
2021-03-02 17:26:24.836 8483-8483/? E/d.process.acor: Not starting debugger since process cannot load the jdwp agent.
2021-03-02 17:26:24.862 8498-8498/? E/viders.calenda: Not starting debugger since process cannot load the jdwp agent.
2021-03-02 17:26:25.016 8059-8112/? E/CarrierServices: [3450] cqf.a: Invalid signature found for com.android.contacts: 18B66F4996F3D01CEAD29D3A3AA81801E7950B82
2021-03-02 17:26:25.035 8059-8112/? E/CarrierServices: [3450] cqf.a: Invalid signature found for com.android.contacts: 18B66F4996F3D01CEAD29D3A3AA81801E7950B82
2021-03-02 17:26:25.221 1791-2347/? E/GnssHAL_GnssInterface: gnssSvStatusCb: a: input svInfo.flags is 8
2021-03-02 17:26:25.221 1791-2347/? E/GnssHAL_GnssInterface: gnssSvStatusCb: b: input svInfo.flags is 8
2021-03-02 17:26:25.247 8050-8050/? E/GmsRequestQueue: Tried to stop global GMSCore RequestQueue. This is likely unintended, so ignoring.
2021-03-02 17:26:25.814 8050-8206/? E/ModuleIdSetter: exception when setting module id
    java.lang.IllegalStateException: Unable to get current module info in ModuleManager created with non-module Context
        at com.google.android.chimera.config.ModuleManager.getCurrentModule(:com.google.android.gms@210214040@21.02.14 (120700-352619232):2)
        at ages.a(:com.google.android.gms@210214040@21.02.14 (120700-352619232):4)
        at agev.aa(:com.google.android.gms@210214040@21.02.14 (120700-352619232):1)
        at agbe.a(Unknown Source:3)
        at sjj.a(:com.google.android.gms@210214040@21.02.14 (120700-352619232):0)
        at sfo.f(:com.google.android.gms@210214040@21.02.14 (120700-352619232):1)
        at sfm.e(:com.google.android.gms@210214040@21.02.14 (120700-352619232):1)
        at sig.p(:com.google.android.gms@210214040@21.02.14 (120700-352619232):2)
        at sig.v(:com.google.android.gms@210214040@21.02.14 (120700-352619232):3)
        at sig.d(:com.google.android.gms@210214040@21.02.14 (120700-352619232):2)
        at sig.a(:com.google.android.gms@210214040@21.02.14 (120700-352619232):7)
        at sig.m(:com.google.android.gms@210214040@21.02.14 (120700-352619232):1)
        at syr.a(:com.google.android.gms@210214040@21.02.14 (120700-352619232):0)
        at sxs.a(:com.google.android.gms@210214040@21.02.14 (120700-352619232):8)
        at sxj.d(:com.google.android.gms@210214040@21.02.14 (120700-352619232):0)
        at sxm.handleMessage(:com.google.android.gms@210214040@21.02.14 (120700-352619232):23)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at afty.iE(:com.google.android.gms@210214040@21.02.14 (120700-352619232):0)
        at afty.dispatchMessage(:com.google.android.gms@210214040@21.02.14 (120700-352619232):10)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)
2021-03-02 17:26:26.221 1791-2347/? E/GnssHAL_GnssInterface: gnssSvStatusCb: a: input svInfo.flags is 8
2021-03-02 17:26:26.221 1791-2347/? E/GnssHAL_GnssInterface: gnssSvStatusCb: b: input svInfo.flags is 8
2021-03-02 17:26:27.221 1791-2347/? E/GnssHAL_GnssInterface: gnssSvStatusCb: a: input svInfo.flags is 8
2021-03-02 17:26:27.221 1791-2347/? E/GnssHAL_GnssInterface: gnssSvStatusCb: b: input svInfo.flags is 8
2021-03-02 17:26:27.709 8167-8404/? E/LocalNetworkId: Can not find ARP file or impossible to read file.
    java.io.FileNotFoundException: proc/net/arp: open failed: EACCES (Permission denied)
        at libcore.io.IoBridge.open(IoBridge.java:496)
        at java.io.FileInputStream.<init>(FileInputStream.java:159)
        at java.io.FileReader.<init>(FileReader.java:72)
        at com.google.android.apps.gsa.search.core.google.a.q.b(SourceFile:71)
        at com.google.android.apps.gsa.search.core.google.a.q.a(SourceFile:23)
        at com.google.android.apps.gsa.staticplugins.g.g.a(Unknown Source:1)
        at com.google.android.apps.gsa.v.d.a.d.call(Unknown Source:2)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at com.google.android.apps.gsa.v.d.a.f.run(SourceFile:16)
        at com.google.android.apps.gsa.v.d.a.n.run(Unknown Source:3)
        at com.google.android.apps.gsa.shared.util.c.b.f.run(Unknown Source:3)
        at com.google.android.apps.gsa.shared.util.c.b.bj.run(SourceFile:3)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
        at com.google.android.apps.gsa.shared.util.c.b.m.run(SourceFile:6)
     Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
        at libcore.io.Linux.open(Native Method)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
        at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7255)
        at libcore.io.IoBridge.open(IoBridge.java:482)
        at java.io.FileInputStream.<init>(FileInputStream.java:159) 
        at java.io.FileReader.<init>(FileReader.java:72) 
        at com.google.android.apps.gsa.search.core.google.a.q.b(SourceFile:71) 
        at com.google.android.apps.gsa.search.core.google.a.q.a(SourceFile:23) 
        at com.google.android.apps.gsa.staticplugins.g.g.a(Unknown Source:1) 
        at com.google.android.apps.gsa.v.d.a.d.call(Unknown Source:2) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at com.google.android.apps.gsa.v.d.a.f.run(SourceFile:16) 
        at com.google.android.apps.gsa.v.d.a.n.run(Unknown Source:3) 
        at com.google.android.apps.gsa.shared.util.c.b.f.run(Unknown Source:3) 
        at com.google.android.apps.gsa.shared.util.c.b.bj.run(SourceFile:3) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
        at com.google.android.apps.gsa.shared.util.c.b.m.run(SourceFile:6) 
```
</details>

**What package are you using? What version?**
Flutter SDK on Android (latest)

**To Reproduce**
1. Download sample app.
2. Run sample flutter
3. Scroll up to load media types.
4. App and scrolling begins to lag.
5. Crashes

**Expected behavior**
Scrolling works without crashing due to media loading.

**Comment by imtoori** [comment]
Hi @searchy2 are you talking about this [demo app](https://github.com/GetStream/flutter-samples/tree/main/stream_chat_v1)?

**Comment by searchy2** [comment]
Yes, that's correct

**Comment by searchy2** [comment]
No, this one here: https://github.com/GetStream/stream-chat-flutter/tree/master/packages/stream_chat_flutter

**Comment by searchy2** [comment]
Any updates?

**Comment by imtoori** [comment]
Hi @searchy2 I'm trying to reproduce the issue, but it's not happening to me

I'm running this https://github.com/GetStream/stream-chat-flutter/tree/master/packages/stream_chat_flutter/example and scrolling up in the list, but nothing is happening

**Comment by sachaarbonel** [comment]
Hey @searchy2 have you tried with another android emulator? See SO response [here](https://stackoverflow.com/questions/22629568/couldnt-load-memtrack-module-logcat-error)

**Comment by searchy2** [comment]
Yes, the crash happens 100% of the time on emulator and physical device.
Let me share a demo video

**Comment by searchy2** [comment]
I've retested and was able to reproduce consistently. 
Please follow the steps outline in the original post.

**Comment by xsahil03x** [comment]
@searchy2 we tried to reproduce again but failed.

Sharing a video we recorded: https://drive.google.com/file/d/18c1lbpGSHDwunZQfdt8WpciaIl40pvMz/view?usp=sharing

**Comment by searchy2** [comment]
Wonderful, scrolling with media no longer crashes when testing with the latest beta and master.
