### ISSUE TITLE
[Help] Getting "Exception: Already connected"

### ISSUE THREAD

**Issue by Abacaxi-Nelson** [GetStream/stream-chat-flutter#366]
Hi all,

Im using: [https://github.com/GetStream/flutter-samples/tree/main/packages/stream_chat_v1](https://github.com/GetStream/flutter-samples/tree/main/packages/stream_chat_v1)

When user is loggedIn, im doing: 
```dart
await streamChatClient.connectUser(
    stream.User(
      id: user.uid,
      extraData: {
        'image': user.imageUrl,
        'name': user.username,
      },
    ),
    response.body,
  );
```

Some user experience exception (im collecting them in a database):

```dart
flutter: Exception: Already connected
flutter: #0      StreamChatClient.connect
package:stream_chat/src/client.dart:486
#1      StreamChatClient.connectUser
package:stream_chat/src/client.dart:405
#2      userProvider.<anonymous closure>
package:amber_app/app/auth_widget.dart:48
<asynchronous suspension>
#3      userProvider.<anonymous closure> (package:amber_app/app/auth_widget.dart)
package:amber_app/app/auth_widget.dart:1
#4      AutoDisposeFutureProviderFamily.create.<anonymous closure>
package:riverpod/…/future_provider/auto_dispose.dart:56
#5      new AutoDisposeProviderBase.<anonymous closure>
package:riverpod/…/framework/auto_dispose.dart:36
#6      ProviderElement._runStateCreate
package:riverpod/…/framework/base_provider.dart:873
#7      ProviderElement.flush
package:riverpod/…/framework/base_provider.dart:656
#8      ProviderSubscription.flush
package:riverpod/…/framework/base_provider.dart:469
#9      _ConsumerState.build
package:flutter_riverpod/src/consumer.dart:282
#10     StatefulElement.build
package:flutter/…/widgets/framework.dart:4744
#11     ComponentElement.performRebuild
package:flutter/…/widgets/framework.dart:4627
#12     StatefulElement.performRebuild
package:flutter/…/widgets/framework.dart:4800
#13     Element.rebuild
package:flutter/…/widgets/framework.dart:4343
#14     BuildOwner.buildScope
package:flutter/…/widgets/framework.dart:2730
#15     WidgetsBinding.drawFrame
package:flutter/…/widgets/binding.dart:913
#16     RendererBinding._handlePersistentFrameCallback
package:flutter/…/rendering/binding.dart:302
#17     SchedulerBinding._invokeFrameCallback
package:flutter/…/scheduler/binding.dart:1117
#18     SchedulerBinding.handleDrawFrame
package:flutter/…/scheduler/binding.dart:1055
#19     SchedulerBinding._handleDrawFrame
package:flutter/…/scheduler/binding.dart:971
#20     _rootRun (dart:async/zone.dart:1190:13)
#21     _CustomZone.run (dart:async/zone.dart:1093:19)
#22     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
```

Is there to detect if user is already connected, and not trigger a `streamChatClient.connectUser`

Thanks, Nelson

**Comment by xsahil03x** [comment]
@Abacaxi-Nelson you can check the current connection status using 
```dart
client.wsConnectionStatus
```

**Comment by Abacaxi-Nelson** [comment]
thanks @xsahil03x 
will try it
