### ISSUE TITLE
stream_chat_flutter_core example

### ISSUE THREAD

**Issue by cdg720** [GetStream/stream-chat-flutter#441]
**Describe the bug**
When I pull up (or down) messages in a channel, I get the following:
```
E/flutter (15560): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: NoSuchMethodError: The method 'call' was called on null.
E/flutter (15560): Receiver: null
E/flutter (15560): Tried calling: call()
E/flutter (15560): #0      _MessageScreenState.build.<anonymous closure> (package:example/main.dart:222:53)
E/flutter (15560): #1      _MessageScreenState.build.<anonymous closure> (package:example/main.dart:221:30)
E/flutter (15560): #2      _LazyLoadScrollViewState._onEndOfPage (package:stream_chat_flutter_core/src/lazy_load_scroll_view.dart:120:27)
E/flutter (15560): #3      _LazyLoadScrollViewState._onNotification (package:stream_chat_flutter_core/src/lazy_load_scroll_view.dart:92:11)
E/flutter (15560): #4      Element.visitAncestorElements (package:flutter/src/widgets/framework.dart:4045:39)
E/flutter (15560): #5      Notification.dispatch (package:flutter/src/widgets/notification_listener.dart:138:13)
E/flutter (15560): #6      DragScrollActivity.dispatchScrollUpdateNotification (package:flutter/src/widgets/scroll_activity.dart:465:139)
E/flutter (15560): #7      ScrollPosition.didUpdateScrollPositionBy (package:flutter/src/widgets/scroll_position.dart:870:15)
E/flutter (15560): #8      ScrollPosition.setPixels (package:flutter/src/widgets/scroll_position.dart:276:9)
E/flutter (15560): #9      ScrollPositionWithSingleContext.setPixels (package:flutter/src/widgets/scroll_position_with_single_context.dart:82:18)
E/flutter (15560): #10     ScrollPositionWithSingleContext.applyUserOffset (package:flutter/src/widgets/scroll_position_with_single_context.dart:124:5)
E/flutter (15560): #11     ScrollDragController.update (package:flutter/src/widgets/scroll_activity.dart:387:14)
E/flutter (15560): #12     ScrollableState._handleDragUpdate (package:flutter/src/widgets/scrollable.dart:646:12)
E/flutter (15560): #13     DragGestureRecognizer._checkUpdate.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:436:55)
E/flutter (15560): #14     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (15560): #15     DragGestureRecognizer._checkUpdate (package:flutter/src/gestures/monodrag.dart:436:7)
E/flutter (15560): #16     DragGestureRecognizer.handleEvent (package:flutter/src/gestures/monodrag.dart:289:9)
E/flutter (15560): #17     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:93:12)
E/flutter (15560): #18     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:138:9)
E/flutter (15560): #19     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:397:8)
E/flutter (15560): #20     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:136:18)
E/flutter (15560): #21     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:122:7)
E/flutter (15560): #22     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:439:19)
E/flutter (15560): #23     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:419:22)
E/flutter (15560): #24     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:287:11)
E/flutter (15560): #25     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
E/flutter (15560): #26     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
E/flutter (15560): #27     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
E/flutter (15560): #28     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
E/flutter (15560): #29     _rootRunUnary (dart:async/zone.dart:1370:13)
E/flutter (15560): #30     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
E/flutter (15560): #31     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
E/flutter (15560): #32     _invoke1 (dart:ui/hooks.dart:182:10)
E/flutter (15560): #33     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:282:7)
E/flutter (15560): #34     _dispatchPointerDataPacket (dart:ui/hooks.dart:96:31)
E/flutter (15560): 
```

**What package are you using? What version?**
stream_chat_flutter_core 1.5.3

**What platform is it about?**
- [v] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS
- [ ] Linux

**To Reproduce**
1. git clone https://github.com/GetStream/stream-chat-flutter.git 
2. in Android studio, open stream-chat-flutter/packages/stream_chat_flutter_core
3. open stream_chat_flutter_core/pubspec.yaml and pub get (i commented out dev_dependencies)
4. run stream_chat_flutter_core/example/lib/main.dart
5. click any channel that has many messages, e.g. Family
6. either pull up or down messages
7. errors

**Expected behavior**
No error.

**Logs**
flutter analyze
```
Analyzing stream_chat_flutter_core...                                   

   info • Sort pub dependencies • example/pubspec.yaml:31:3 • sort_pub_dependencies

1 issue found. (ran in 0.7s)
```

Paste the output of running `flutter doctor -v` here.
```
[✓] Flutter (Channel stable, 2.2.0, on Linux, locale en_US.UTF-8)
    • Flutter version 2.2.0 at /home/dokook/development/tools/flutter
    • Framework revision b22742018b (4 days ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/dokook/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /snap/android-studio/current/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /snap/android-studio/103/android-studio
    • Flutter plugin version 56.0.2
    • Dart plugin version 202.8488
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)

[✓] Android Studio
    • Android Studio at /snap/android-studio/current/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /snap/android-studio/current/android-studio
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)

[✓] Connected device (2 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 90.0.4430.212

• No issues found!
```

**Comment by imtoori** [comment]
Hi @cdg720 thanks for reporting the issue
However, this has been fixed in the `develop` branch and it will be soon merged to master
You can `git checkout develop` if you don't want to wait
