### ISSUE TITLE
Bad state: Cannot add new events after calling close

### ISSUE THREAD

**Issue by brizaldi** [GetStream/stream-chat-flutter#45]
i got this error message when using the alpha version

```
E/flutter (31659): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Bad state: Cannot add new events after calling close
E/flutter (31659): #0      _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:251:24)
E/flutter (31659): #1      Subject._add (package:rxdart/src/subjects/subject.dart:141:17)
E/flutter (31659): #2      Subject.add (package:rxdart/src/subjects/subject.dart:135:5)
E/flutter (31659): #3      ChannelsBlocState.queryChannels.<anonymous closure> (package:stream_chat_flutter/src/channels_bloc.dart:90:31)
E/flutter (31659): #4      _rootRunUnary (dart:async/zone.dart:1192:38)
E/flutter (31659): #5      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter (31659): #6      _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
E/flutter (31659): #7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (31659): #8      _DelayedData.perform (dart:async/stream_impl.dart:594:14)
E/flutter (31659): #9      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:710:11)
E/flutter (31659): #10     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:670:7)
E/flutter (31659): #11     _rootRun (dart:async/zone.dart:1180:38)
E/flutter (31659): #12     _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter (31659): #13     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
E/flutter (31659): #14     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
E/flutter (31659): #15     _rootRun (dart:async/zone.dart:1184:13)
E/flutter (31659): #16     _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter (31659): #17     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
E/flutter (31659): #18     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
E/flutter (31659): #19     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
E/flutter (31659): #20     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
```

the chat functionality still working fine though

**Comment by apgapg** [comment]
To better handle this I have created certain extensions on BehaviorSubject:
https://gist.github.com/apgapg/a520872c263b70bcfec52da0d7c221ec

**Comment by imtoori** [comment]
This should not happen anymore
Feel free to reopen it if you're still facing it

**Comment by rohan20** [comment]
@imtoori This still occurs on `^0.2.21`.
