### ISSUE TITLE
Cannot build MessageActionsModal

### ISSUE THREAD

**Issue by ericderegt** [GetStream/stream-chat-flutter#463]
**Describe the bug**
I'm trying to use the modal actions in my chat application. I've followed the documentation and the application works fine to send messages. However when I try to hold down on a message to see the modal actions the application throws an exception 

`The following _Exception was thrown building MessageActionsModal(dirty,
dependencies: [MediaQuery],
state: _MessageActionsModalState#b36d5):
Exception: You must have a StreamChat widget at the top of your widget tree`

**What package are you using? What version?**
stream_chat_flutter: ^2.0.0-nullsafety.3

**What platform is it about?**
- [ ] Android
- [x] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS
- [ ] Linux

**To Reproduce**
1. Click on Chat button which builds StreamChat
2. Send message
3. Hold down on message

**Expected behavior**
Should show modal actions

**Code**
Navigate to stream chat
```
  _onPressedChat(
      BuildContext context, StreamChatClient client, Channel channel) async {
    final result =
        await Navigator.push(context, MaterialPageRoute(builder: (context) {
      return StreamChat(
        client: client,
        child: StreamChannel(
          channel: channel,
          child: ChannelPage(key: Key("abc")),
        ),
      );
    }));
  }
```

Channel page
```
class ChannelPage extends StatelessWidget {
  const ChannelPage({
    required Key key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: ChannelHeader(
        onBackPressed: () => Navigator.pop(context),
      ),
      body: Column(
        children: <Widget>[
          Expanded(
            child: MessageListView(),
          ),
          MessageInput(),
        ],
      ),
    );
  }
}
```

**Logs **
```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY
╞═══════════════════════════════════════════════════════════
The following _Exception was thrown building MessageActionsModal(dirty,
dependencies: [MediaQuery],
state: _MessageActionsModalState#b36d5):
Exception: You must have a StreamChat widget at the top of your widget tree

The relevant error-causing widget was:
  MessageActionsModal
  file:///Users/ericderegt/.pub-cache/hosted/pub.dartlang.org/stream_chat_flutter-2
  .0.0-nullsafety.3/lib/src/message_widget.dart:855:20

When the exception was thrown, this was the stack:
#0      StreamChat.of (package:stream_chat_flutter/src/stream_chat.dart:67:7)
#1      _MessageActionsModalState._showMessageOptionsModal
(package:stream_chat_flutter/src/message_actions_modal.dart:80:29)
#2      _MessageActionsModalState.build
(package:stream_chat_flutter/src/message_actions_modal.dart:75:12)
#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4691:27)
#4      ComponentElement.performRebuild
```

Paste the output of running `flutter doctor -v` here.
```
[✓] Flutter (Channel stable, 2.2.0, on Mac OS X 10.15.7 19H1030 darwin-x64, locale en-US)
    • Flutter version 2.2.0 at /Users/ericderegt/development/flutter
    • Framework revision b22742018b (2 weeks ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/ericderegt/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.0.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.56.2)
    • VS Code at /Users/ericderegt/Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (2 available)
    • iPhone 12 Pro Max (mobile) • C27AF448-5964-428B-9336-7C86A70D1AD7 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome
      91.0.4472.77

! Doctor found issues in 1 category.
```

**Comment by ericderegt** [comment]
This was resolved but putting StreamChat in the Material builder as in https://github.com/GetStream/stream-chat-flutter/issues/47. Is there an update on when there will be a new solution for dealing with this other than using the builder?
