### ISSUE TITLE
WebsocketChannelException

### ISSUE THREAD

**Issue by rlee1990** [GetStream/stream-chat-flutter#599]
**Describe the bug**
I am getting the below error:
`WebSocketError(message: WebSocketChannelException: SocketException: Failed host lookup: 'chat-us-east-1.stream-io-api.com' (OS Error: No address associated with hostname, errno = 7))`

```
W/Firestore(12965): (23.0.1) [WatchStream]: (158e4b8) Stream closed with status: Status{code=UNAVAILABLE, description=Unable to resolve host firestore.googleapis.com, cause=java.lang.RuntimeException: java.net.UnknownHostException: Unable to resolve host "firestore.googleapis.com": No address associated with hostname
W/Firestore(12965): 	at io.grpc.internal.DnsNameResolver.resolveAll(DnsNameResolver.java:436)
W/Firestore(12965): 	at io.grpc.internal.DnsNameResolver$Resolve.resolveInternal(DnsNameResolver.java:272)
W/Firestore(12965): 	at io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:228)
W/Firestore(12965): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/Firestore(12965): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/Firestore(12965): 	at java.lang.Thread.run(Thread.java:764)
W/Firestore(12965): Caused by: java.net.UnknownHostException: Unable to resolve host "firestore.googleapis.com": No address associated with hostname
W/Firestore(12965): 	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:157)
W/Firestore(12965): 	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:105)
W/Firestore(12965): 	at java.net.InetAddress.getAllByName(InetAddress.java:1154)
W/Firestore(12965): 	at io.grpc.internal.DnsNameResolver$JdkAddressResolver.resolveAddress(DnsNameResolver.java:646)
W/Firestore(12965): 	at io.grpc.internal.DnsNameResolver.resolveAll(DnsNameResolver.java:404)
W/Firestore(12965): 	... 5 more
W/Firestore(12965): Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
W/Firestore(12965): 	at libcore.io.Linux.android_getaddrinfo(Native Method)
W/Firestore(12965): 	at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:172)
W/Firestore(12965): 	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:137)
W/Firestore(12965): 	... 9 more
```
It was working an hour before.

**Comment by rlee1990** [comment]
Working again. Keeping open to see what really went on wouldn't want this issue in production.

**Comment by xsahil03x** [comment]
This is likely due to internet connection not available or maybe the firestore api was down.

**Comment by rlee1990** [comment]
I was thinking that as I was reading the error but from why I could search all services was up but I'll close this out.

**Comment by emmett-deen** [comment]
Having this issue now
