### ISSUE TITLE
Unhandled Exception: SqliteException(5): database is locked

### ISSUE THREAD

**Issue by hiashutoshsingh** [GetStream/stream-chat-flutter#600]
**Describe the bug**
Stream package throws error randomly, it is happening for the last 2 weeks when I updated to the latest stream core version. I have to disconnect to stream and then connectt again to make it work. What could be the issue here from my side?

**What package are you using? What version?**
```
  stream_chat_flutter_core: 2.0.0-nullsafety.9
  stream_chat_persistence: 2.0.0-nullsafety.8
  firebase_core: 1.0.2
  firebase_analytics: 7.1.1
  firebase_messaging: 9.0.1
```

**What platform is it about?**
- [x] Android
- [x] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS
- [ ] Linux

**Logs**
```
E/flutter ( 8029): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: SqliteException(5): database is locked
E/flutter ( 8029): #0      DatabaseImpl.execute (package:sqlite3/src/impl/database.dart:119:9)
E/flutter ( 8029): #1      DatabaseImpl.userVersion= (package:sqlite3/src/impl/database.dart:84:5)
E/flutter ( 8029): #2      _VmVersionDelegate.setSchemaVersion (package:moor/src/ffi/vm_database.dart:252:14)
E/flutter ( 8029): #3      DelegatedDatabase._runMigrations (package:moor/src/runtime/executor/helpers/engines.dart:304:29)
E/flutter ( 8029): <asynchronous suspension>
E/flutter ( 8029): #4      DelegatedDatabase.ensureOpen.<anonymous closure> (package:moor/src/runtime/executor/helpers/engines.dart:267:7)
E/flutter ( 8029): <asynchronous suspension>
E/flutter ( 8029): #5      Lock.synchronized.callBlockAndComplete (package:moor/src/utils/synchronized.dart:18:16)
E/flutter ( 8029): <asynchronous suspension>
E/flutter ( 8029): #6      ServerImplementation._handleEnsureOpen (package:moor/src/runtime/remote/server_impl.dart:117:12)
E/flutter ( 8029): <asynchronous suspension>
E/flutter ( 8029): #7      MoorCommunication.setRequestHandler.<anonymous closure>.<anonymous closure> (package:moor/src/runtime/remote/communication.dart)
E/flutter ( 8029): <asynchronous suspension>
E/flutter ( 8029): 
E/flutter ( 8029): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: SqliteException(5): database is locked
E/flutter ( 8029): #0      DatabaseImpl.execute (package:sqlite3/src/impl/database.dart:119:9)
E/flutter ( 8029): #1      DatabaseImpl.userVersion= (package:sqlite3/src/impl/database.dart:84:5)
E/flutter ( 8029): #2      _VmVersionDelegate.setSchemaVersion (package:moor/src/ffi/vm_database.dart:252:14)
E/flutter ( 8029): #3      DelegatedDatabase._runMigrations (package:moor/src/runtime/executor/helpers/engines.dart:304:29)
E/flutter ( 8029): <asynchronous suspension>
E/flutter ( 8029): #4      DelegatedDatabase.ensureOpen.<anonymous closure> (package:moor/src/runtime/executor/helpers/engines.dart:267:7)
E/flutter ( 8029): <asynchronous suspension>
E/flutter ( 8029): #5      Lock.synchronized.callBlockAndComplete (package:moor/src/utils/synchronized.dart:18:16)
E/flutter ( 8029): <asynchronous suspension>
E/flutter ( 8029): #6      ServerImplementation._handleEnsureOpen (package:moor/src/runtime/remote/server_impl.dart:117:12)
E/flutter ( 8029): <asynchronous suspension>
E/flutter ( 8029): #7      MoorCommunication.setRequestHandler.<anonymous closure>.<anonymous closure> (package:moor/src/runtime/remote/communication.dart)
E/flutter ( 8029): <asynchronous suspension>
E/flutter ( 8029): 
E/flutter ( 8029): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: SqliteException(5): database is locked
E/flutter ( 8029): #0      DatabaseImpl.execute (package:sqlite3/src/impl/database.dart:119:9)
E/flutter ( 8029): #1      DatabaseImpl.userVersion= (package:sqlite3/src/impl/database.dart:84:5)
E/flutter ( 8029): #2      _VmVersionDelegate.setSchemaVersion (package:moor/src/ffi/vm_database.dart:252:14)
E/flutter ( 8029): #3      DelegatedDatabase._runMigrations (package:moor/src/runtime/executor/helpers/engines.dart:304:29)
E/flutter ( 8029): <asynchronous suspension>
E/flutter ( 8029): #4      DelegatedDatabase.ensureOpen.<anonymous closure> (package:moor/src/runtime/executor/helpers/engines.dart:267:7)
E/flutter ( 8029): <asynchronous suspension>
E/flutter ( 8029): #5      Lock.synchronized.callBlockAndComplete (package:moor/src/utils/synchronized.dart:18:16)
E/flutter ( 8029): <asynchronous suspension>
E/flutter ( 8029): #6      ServerImplementation._handleEnsureOpen (package:moor/src/runtime/remote/server_impl.dart:117:12)
E/flutter ( 8029): <asynchronous suspension>
E/flutter ( 8029): #7      MoorCommunication.setRequestHandler.<anonymous closure>.<anonymous closure> (package:moor/src/runtime/remote/communication.dart)
E/flutter ( 8029): <asynchronous suspension>
```

 `flutter doctor -v` 

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.2.3 20D91 darwin-x64, locale
    en-IN)
    • Flutter version 2.2.3 at /Users/i0868/Documents/flutter
    • Framework revision f4abaa0735 (2 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/i0868/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Connected device (2 available)
    • iPhone 11 (mobile) • E228B37F-4D7D-46CF-AC60-1F325F972977 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)       • chrome                               • web-javascript
      • Google Chrome 91.0.4472.114

• No issues found!
```

@imtoori

**Comment by deven98** [comment]
Hey @hiashutoshsingh 👋 ,

Just to confirm: does this happen in development or on a physical device as well?
If it happens only on dev, can you try reinstalling the apk/ipa file on the emulator? 

Thanks.

**Comment by hiashutoshsingh** [comment]
Hey @deven98 , thanks for responding.
Till now I haven't observed this issue on the release build. It happened in the physical device and in the emulator for the dev build. 
I have installed the release build in my physical device I will let you know if that happens in the release build too.

**Comment by deven98** [comment]
Please try a reinstall of the app on the emulator and also let us know if it affects anything on any release build. 

Just to confirm, did the emulator app work fine regardless of the error or did it stall app loading?

**Comment by hiashutoshsingh** [comment]
Sure.
No, it didn't work it was throwing an error, I had to disconnect to stream-sdk then connect again.

**Comment by imtoori** [comment]
It's happened to me but rarely and usually after some weird hot reload
Can you confirm that's case even for you? @hiashutoshsingh

**Comment by hiashutoshsingh** [comment]
Yes, after hot reload and sometimes starting application after killing it. @imtoori

**Comment by imtoori** [comment]
I don't think we do anything strange that causes this issue
It's likely due to a weird hot-reload behaviour

I'll leave this open for the moment so that if we get to know more about this we can post an update, but I think we'll eventually close this if this is the only cause

**Comment by hiashutoshsingh** [comment]
It happened today, I was creating a group and suddenly everything stops working and after hot-reloading I got same error in the console.

**Comment by xsahil03x** [comment]
Closing as it's likely due to `hot-reload`. Feel free to open it if appears on a release build.
