### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by marcossevilla** [GetStream/stream-chat-flutter#674]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS

### What version are you using?

package:stream_chat_flutter - ^2.0.0

### What happened?

Throws this error:

```
══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞══
The following _CastError was thrown during a scheduler callback:
Null check operator used on a null value

When the exception was thrown, this was the stack:
#0      ItemScrollController.jumpTo (package:scrollable_positioned_list/src/scrollable_positioned_list.dart:195:25)
#1      _MessageListViewState.didChangeDependencies.<anonymous closure> (package:stream_chat_flutter/src/message_list_view.dart:1202:28)
#2      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1143:15)
#3      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1088:9)
#4      AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:1006:9)
#7      TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#8      AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:993:27)
#9      WidgetTester.pumpWidget.<anonymous closure> (package:flutter_test/src/widget_tester.dart:554:22)
#12     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#13     WidgetTester.pumpWidget (package:flutter_test/src/widget_tester.dart:551:27)
#14     main.<anonymous closure>.<anonymous closure> 
```

in this widget test:

```dart
late stream_chat_flutter.StreamChatClient client;
late stream_chat_flutter.Channel channel;

setUp(() {
  client = MockStreamChatClient();
  when(() => client.on(any(), any(), any(), any()))
      .thenAnswer((_) => const Stream.empty());
  channel = MockChannel();
  when(() => channel.initialized).thenAnswer((_) async => true);
  when(() => channel.on(any(), any(), any(), any())).thenAnswer(
    (_) => const Stream.empty(),
  );
  final channelClientState = MockChannelClientState();
  when(() => channel.state).thenReturn(channelClientState);
  when(() => channelClientState.threadsStream).thenAnswer(
    (_) => const Stream.empty(),
  );
  when(() => channelClientState.messagesStream).thenAnswer(
    (_) => const Stream.empty(),
  );
  when(() => channelClientState.messages).thenReturn([]);
  when(() => channelClientState.isUpToDate).thenReturn(true);
});

...

testWidgets('renders message list view', (tester) async {
    await tester.pumpWidget(
      MaterialApp(
        home: stream_chat_flutter.StreamChat(
          client: client,
          child: MessageListView(channel: channel),
        ),
      ),
    );
    await tester.pumpAndSettle();
    expect(find.byType(stream_chat_flutter.MessageListView), findsOneWidget);
});
```

`MessageListView` is a widget that wraps up a StreamChart `MessageListView`.

### Steps to reproduce

```bash
1. Run this test on a `MessageListView`.
```

### Supporting info to reproduce

Apparently it's on line 1201 of `message_list_view.dart`:

```dart
WidgetsBinding.instance!.addPostFrameCallback((timeStamp) {
    _scrollController?.jumpTo(
        index: initialIndex,
        alignment: initialAlignment,
    );
});
```

### Relevant log output

```shell
══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞══
The following _CastError was thrown during a scheduler callback:
Null check operator used on a null value

When the exception was thrown, this was the stack:
#0      ItemScrollController.jumpTo (package:scrollable_positioned_list/src/scrollable_positioned_list.dart:195:25)
#1      _MessageListViewState.didChangeDependencies.<anonymous closure> (package:stream_chat_flutter/src/message_list_view.dart:1202:28)
#2      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1143:15)
#3      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1088:9)
#4      AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:1006:9)
#7      TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#8      AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:993:27)
#9      WidgetTester.pumpWidget.<anonymous closure> (package:flutter_test/src/widget_tester.dart:554:22)
#12     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#13     WidgetTester.pumpWidget (package:flutter_test/src/widget_tester.dart:551:27)
#14     main.<anonymous closure>.<anonymous closure>
```

### Flutter analyze output

```shell
No issues found! (ran in 2.5s)
```

### Flutter doctor output

```shell
[✓] Flutter (Channel beta, 2.5.0-5.2.pre, on macOS 11.5 20G71 darwin-arm, locale
    en)
    • Flutter version 2.5.0-5.2.pre at /Users/marcossevilla/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 19c61fed0d (3 weeks ago), 2021-08-18 17:10:31 -0700
    • Engine revision 7a4c4505f6
    • Dart version 2.14.0 (build 2.14.0-377.7.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/marcossevilla/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.60.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 11.5 20G71 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 93.0.4577.63

! Doctor found issues in 1 category.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by deven98** [comment]
Hey @marcossevilla, 

I'm taking a look into this, might have a few different possible causes. 
I'll let you know when I have more information.

Thanks.
