### ISSUE TITLE
Picture upload always ends with upload errors on iOS 12.5.5

### ISSUE THREAD

**Issue by matthewfx** [GetStream/stream-chat-flutter#747]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS

### What version are you using?

stream_chat_flutter: ^3.1.1

### What happened?

When trying to upload any picture from the photo library on iPhone 5s (iOS 12.5.5) every time it ends up with an upload error. 

### Steps to reproduce

```bash
Go to any channel and try to upload any picture from the photo library
```

### Relevant log output

```shell
2021-10-23 12:09:49.629075+1300 Runner[1714:210519] flutter: 2021-10-23 12:09:49.628746 🚨 🕸️
2021-10-23 12:09:49.630157+1300 Runner[1714:210519] flutter: 2021-10-23 12:09:49.629999 🚨 🕸️ ╔╣ DioError ║ DioErrorType.connectTimeout
2021-10-23 12:09:49.630907+1300 Runner[1714:210519] flutter: 2021-10-23 12:09:49.630689 🚨 🕸️ ║  Connecting timed out [6000ms]
2021-10-23 12:09:49.631608+1300 Runner[1714:210519] flutter: 2021-10-23 12:09:49.631461 🚨 🕸️ ╚════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╝
2021-10-23 12:09:49.634479+1300 Runner[1714:210519] flutter: 2021-10-23 12:09:49.634239 🚨 🕸️
2021-10-23 12:09:49.635350+1300 Runner[1714:210519] flutter: 2021-10-23 12:09:49.635032 🚨 🕸️ ╔╣ Request ║ POST
2021-10-23 12:09:49.636011+1300 Runner[1714:210519] flutter: 2021-10-23 12:09:49.635814 🚨 🕸️ ║  https://chat-us-east-1.stream-io-api.com/channels/messaging/!members-BTfPy4G82uzEUiCsKSv4BjUuHVAKIE6_eLZG8UhRyto/image?api_key=qvctq2qnky68&user_id=a1a244cc-3f27-43be-acbd-c997a5fd97ad&connection_id=616e9b53-0a05-1ce9-0000-0000010124c1
2021-10-23 12:09:49.636780+1300 Runner[1714:210519] flutter: 2021-10-23 12:09:49.636626 🚨 🕸️ ╚════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╝
2021-10-23 12:09:49.646600+1300 Runner[1714:210519] flutter: 2021-10-23 12:09:49.646338 🚨 📡 error uploading the attachment
2021-10-23 12:09:49.648899+1300 Runner[1714:210519] flutter: StreamChatNetworkError(code: -1, message: Connecting timed out [6000ms])
2021-10-23 12:09:49.649967+1300 Runner[1714:210519] flutter: #0      StreamHttpClient.post (package:stream_chat/src/core/http/stream_http_client.dart:158:7)
<asynchronous suspension>
#1      StreamHttpClient.postFile (package:stream_chat/src/core/http/stream_http_client.dart:245:22)
<asynchronous suspension>
#2      StreamAttachmentFileUploader.sendImage (package:stream_chat/src/core/api/attachment_file_uploader.dart:73:22)
<asynchronous suspension>
#3      Future.wait.<anonymous closure> (dart:async/future.dart)
```

### Flutter analyze output

```shell
Analyzing ios...
No issues found! (ran in 1.1s)
```

### Flutter doctor output

```shell
Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-arm, locale
    en-AU)
    • Flutter version 2.5.3 at /Users/mat/Flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (7 days ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mat/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode 12.5.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (2 available)
    • iPhone 12 Pro (mobile) • ACB8F949-7E39-45D3-B882-F08F9DD12E4D • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • Chrome (web)           • chrome                               •
      web-javascript • Google Chrome 94.0.4606.81
    ! Error: Mat's iPhone is not connected. Xcode will continue when Mat's
      iPhone is connected. (code -13)
    ! Error: Mat's iPhone is not connected. Xcode will continue when Mat's
      iPhone is connected. (code -13)

• No issues found!
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by imtoori** [comment]
hi @matthewfx
I'm trying reproducing this bug, but I'm not managing to do it
for context: I tried using the sample app you can find here https://github.com/GetStream/flutter-samples/tree/main/packages/stream_chat_v1
