### ISSUE TITLE
Issue in FilePicker on flutter web

### ISSUE THREAD

**Issue by akul1994** [GetStream/stream-chat-flutter#781]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

Web

### What version are you using?

3.2.0

### What happened?

Unable to upload images using MessageInput,
Gives the following error[](url)

```main.dart.js:17807 Uncaught       On web `path` is always `null`,
      You should access `bytes` property instead,
      Read more about it [here](https://github.com/miguelpruivo/flutter_file_picker/wiki/FAQ)
      
    at Object.c (https://td-flutter-web-prod.web.app/main.dart.js:17807:3)
    at Object.d (https://td-flutter-web-prod.web.app/main.dart.js:17814:14)
    at https://td-flutter-web-prod.web.app/main.dart.js:132894:3
    at bC3.a (https://td-flutter-web-prod.web.app/main.dart.js:27349:62)
    at bC3.$2 (https://td-flutter-web-prod.web.app/main.dart.js:57196:14)
    at bAG.$1 (https://td-flutter-web-prod.web.app/main.dart.js:57190:21)
    at aqE.rT (https://td-flutter-web-prod.web.app/main.dart.js:58651:33)
    at blK.$0 (https://td-flutter-web-prod.web.app/main.dart.js:57680:11)
    at Object.Kr (https://td-flutter-web-prod.web.app/main.dart.js:27483:40)
    at af.tk (https://td-flutter-web-prod.web.app/main.dart.js:57600:3)```
    
    
    Issue seems to be in the filepicker plugin, 
    FIx has been given by the developer too,
    Can you please do the same in the next update?
    
    (https://github.com/miguelpruivo/flutter_file_picker/wiki/FAQ)

### Steps to reproduce

```bash
1. Go to Any Channel
2. Click on attachment icon in message input
3. Try to upload an image
...
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by deven98** [comment]
Hey @akul1994,

This issue has already been fixed and should be in the next release. (https://github.com/GetStream/stream-chat-flutter/pull/763)
Please use the develop branch if you require the fix urgently. 

Best,
Deven
