### ISSUE TITLE
Bug while deleting and recreating the same user

### ISSUE THREAD

**Issue by luvishq** [GetStream/stream-chat-flutter#850]
### Which packages are you using?

stream_chat

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

2.0.0

### What happened?

I deleted a user from the dashboard to test if i can add the user fresh but the api gave me error that user was permanently deleted, is there a way to re-add a permanently deleted user with the same id ?

### Steps to reproduce

```bash
1. Go to stream dashboard
2. Click on delete a user permanently
3. Try to create the user with same id 

It should allow to create the fresh user with that id but the got the below exception in console
```

### Supporting info to reproduce

N/A

### Relevant log output

```shell
E/flutter ( 4207): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: StreamChatNetworkError(code: 16, message: GetOrCreateChannel failed with error: "the user 8ZqAJhtH3HbKQmnRLqGPAXFeCOp2 was deleted", statusCode: 404, data: ErrorResponse(code: 16, message: GetOrCreateChannel failed with error: "the user 8ZqAJhtH3HbKQmnRLqGPAXFeCOp2 was deleted", statusCode: 404, moreInfo: https://getstream.io/chat/docs/api_errors_response))
E/flutter ( 4207): #0      StreamHttpClient.post (package:stream_chat/src/core/http/stream_http_client.dart:158:7)
E/flutter ( 4207): <asynchronous suspension>
E/flutter ( 4207): #1      ChannelApi.queryChannel (package:stream_chat/src/core/api/channel_api.dart:36:22)
E/flutter ( 4207): <asynchronous suspension>
E/flutter ( 4207): #2      Channel.query (package:stream_chat/src/client/channel.dart:1248:28)
E/flutter ( 4207): <asynchronous suspension>
E/flutter ( 4207): #3      Channel.watch (package:stream_chat/src/client/channel.dart:1128:18)
E/flutter ( 4207): <asynchronous suspension>
```

### Flutter analyze output

```shell
N/A
```

### Flutter doctor output

```shell
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.6 20G165 darwin-x64, locale en-US)
    • Flutter version 2.8.1 at /Users/laavaans/Downloads/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (4 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at
    • Platform android-31, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Android Studio
    • Android Studio at /Users/laavaans/Downloads/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] VS Code (version 1.52.1)
    • VS Code at 
    • Flutter extension version 3.18.0

[✓] Connected device (3 available)

• No issues found!
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luvishq** [comment]
Just checked the documentation, we cannot use the same id again, but can you explain why is that so ?

**Comment by imtoori** [comment]
hey @luvishq this is not a bug, it's like this by design. 
There are multiple cases that could bring some conflicts if we were to allow this
