### ISSUE TITLE
SqliteException(5): database is locked

### ISSUE THREAD

**Issue by ManasviPatidar** [GetStream/stream-chat-flutter#943]
### Which packages are you using?

stream_chat_flutter, stream_chat_persistance

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

stream_chat_flutter: ^3.3.2
stream_chat_persistence: ^3.0.0

### What happened?

Received the following exception on sentry.

- This exception is thrown while rendering the ChannelListView Widget.
- The default errorBuilder widget is rendered but nothing happens on refreshing.
- We have received 172 events of this error from 17 users.
- 100% of these exceptions are from Android devices.

### Steps to reproduce

```bash
...
```

### Relevant log output

```shell
String: SqliteException(5): database is locked
  Causing statement: PRAGMA user_version = 6;
  File "database.dart", line 129, in DatabaseImpl.execute
  File "database.dart", line 91, in DatabaseImpl.userVersion=
  File "database.dart", line 256, in _VmVersionDelegate.setSchemaVersion
  File "engines.dart", line 326, in DelegatedDatabase._runMigrations
  File "<asynchronous suspension>"
  File "engines.dart", line 290, in DelegatedDatabase.ensureOpen.<fn>
  File "<asynchronous suspension>"
  File "synchronized.dart", line 18, in Lock.synchronized.callBlockAndComplete
  File "<asynchronous suspension>"
  File "server_impl.dart", line 121, in ServerImplementation._handleEnsureOpen
  File "<asynchronous suspension>"
  File "communication.dart", line 145, in DriftCommunication.setRequestHandler.<fn>.<fn>
```

### Flutter analyze output

```shell
Analyzing apollo...                                                     
No issues found! (ran in 3.5s)
```

### Flutter doctor output

```shell
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.1 21C52 darwin-arm, locale en-IN)
    • Flutter version 2.5.3 at /Users/manasvi/Library/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (5 months ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/manasvi/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.2.1, Build version 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.65.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 98.0.4758.109

• No issues found!
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xsahil03x** [comment]
@ManasviPatidar are these logs from a release build?

**Comment by ManasviPatidar** [comment]
Yes, this was captured by Sentry on release versions of our app.
<img width="833" alt="image" src="https://user-images.githubusercontent.com/43138335/157047426-1902f0b7-b67f-4fea-9040-d5026b37a533.png">

**Comment by GroovinChip** [comment]
@ManasviPatidar are you still having this issue?

**Comment by ManasviPatidar** [comment]
Yes, Still facing this issue in `stream_chat_persistence:3.0.0`, will try in `stream_chat_persistence:3.1.0`.

**Comment by ManasviPatidar** [comment]
@GroovinChip still facing the issue with `stream_chat_persistence:3.1.0`.

**Comment by GroovinChip** [comment]
Are you able to reproduce the issue in a small code sample outside of your main project? If so, would you mind sharing this please?

**Comment by hajajmaor** [comment]
Happening on debug
<details>
  <summary> pubspec.yaml </summary>

```yaml
  stream_chat_flutter_core: ^6.8.0
  stream_chat_persistence: ^6.8.0
```

</details>

<details>
  <summary> Partial log </summary>

```
E/flutter (29575): #6      DatabaseConnectionUser.transaction.<anonymous closure>.<anonymous closure>
connection_user.dart:467
E/flutter (29575): <asynchronous suspension>
E/flutter (29575): #7      DatabaseConnectionUser.transaction
connection_user.dart:460
E/flutter (29575): <asynchronous suspension>
E/flutter (29575):
E/flutter (29575): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: SqliteException(5): while executing statement, database is locked, database is locked (code 5)
E/flutter (29575):   Causing statement: DELETE FROM "members" WHERE "channel_cid" IN (?);, parameters: messaging:XXXXXXX
E/flutter (29575): #0      DriftCommunication.request
communication.dart:113
E/flutter (29575): #1      _BaseExecutor.runBatched
client_impl.dart:80
E/flutter (29575): #2      Batch._runWith
batch.dart:215
E/flutter (29575): #3      Batch._commit
batch.dart:207
E/flutter (29575): <asynchronous suspension>
E/flutter (29575): #4      Future.wait.<anonymous closure> (dart:async/future.dart:525:21)
E/flutter (29575): <asynchronous suspension>
E/flutter (29575): #5      ChatPersistenceClient.updateChannelStates
chat_persistence_client.dart:297
E/flutter (29575): <asynchronous suspension>
E/flutter (29575): #6      DatabaseConnectionUser.transaction.<anonymous closure>.<anonymous closure>
connection_user.dart:467
E/flutter (29575): <asynchronous suspension>
E/flutter (29575): #7      DatabaseConnectionUser.transaction
connection_user.dart:460
E/flutter (29575): <asynchronous suspension>
E/flutter (29575):
E/flutter (29575): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: SqliteException(5): while executing statement, database is locked, database is locked (code 5)
E/flutter (29575):   Causing statement: DELETE FROM "members" WHERE "channel_cid" IN (?);, parameters: messaging:XXXXXXX
E/flutter (29575): #0      DriftCommunication.request
communication.dart:113
E/flutter (29575): #1      _BaseExecutor.runBatched
client_impl.dart:80
E/flutter (29575): #2      Batch._runWith
batch.dart:215
E/flutter (29575): #3      Batch._commit
batch.dart:207
E/flutter (29575): <asynchronous suspension>
E/flutter (29575): #4      Future.wait.<anonymous closure> (dart:async/future.dart:525:21)
E/flutter (29575): <asynchronous suspension>
E/flutter (29575): #5      ChatPersistenceClient.updateChannelStates
chat_persistence_client.dart:297
E/flutter (29575): <asynchronous suspension>
E/flutter (29575): #6      DatabaseConnectionUser.transaction.<anonymous closure>.<anonymous closure>
connection_user.dart:467
E/flutter (29575): <asynchronous suspension>
E/flutter (29575): #7      DatabaseConnectionUser.transaction
connection_user.dart:460
E/flutter (29575): <asynchronous suspension>
E/flutter (29575):
E/flutter (29575): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: SqliteException(5): while executing statement, database is locked, database is locked (code 5)
E/flutter (29575):   Causing statement: DELETE FROM "members" WHERE "channel_cid" 
```

</details>
