### ISSUE TITLE
Unhandled Exception: Unsupported operation: Cannot remove from a fixed-length list

### ISSUE THREAD

**Issue by navneetdhameliya** [GetStream/stream-chat-flutter#969]
### Which packages are you using?

stream_chat, stream_chat_flutter, stream_chat_localizations

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

stream_chat: ^3.3.1
  stream_chat_flutter: ^3.3.2
  stream_chat_localizations: ^2.0.0

### What happened?

Hello GetStream team
Actually i have multiple reaction to message functionality in my app so i can add multiple reaction on message but when i try to remove reaction using deleteReaction method of strem_chat plugin that give me error Unsupported operation: Cannot remove from a fixed-length list so i can't delete multiple reaction in my app

Please resolve my issue

![Screenshot 2022-03-09 at 10 39 29 AM](https://user-images.githubusercontent.com/93118368/157377376-4f65a0e4-e023-4c9d-bccd-29e17ea41e47.png)

### Steps to reproduce

```bash
1. Go to '...'
2. Click on '...'
3. Scroll down to '...'
...
```

### Supporting info to reproduce

bool isReacted = await getReactionResult(
        message: controller.selectedQuotedMessage.value,
        reaction: emoji.name.replaceAll(" ", "_"));
    if (isReacted) {
      controller.channel.value.deleteReaction(
          controller.selectedQuotedMessage.value,
          Reaction(type: emoji.name.replaceAll(" ", "_"),));
    } else {
      controller.channel.value.sendReaction(
          controller.selectedQuotedMessage.value,
          emoji.name.replaceAll(" ", "_"));
    }

this is my code for delete reaction on message if given reaction is already given by user and if not then add reaction

### Relevant log output

```shell
E/flutter (15033): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Unsupported operation: Cannot remove from a fixed-length list
E/flutter (15033): #0      FixedLengthListMixin.removeWhere (dart:_internal/list.dart:46:5)
E/flutter (15033): #1      Channel.deleteReaction (package:stream_chat/src/client/channel.dart:902:10)
E/flutter (15033): #2      ConversationScreen.getReplyToMessageWidget.<anonymous closure> (package:hubble/UI/screens/ConversationSectionScreen/SingleConversationScreen/views/single_conversation_views.dart:1077:56)
E/flutter (15033): <asynchronous suspension>
E/flutter (15033):
```

### Flutter analyze output

```shell
there are so many errors in flutter analyze but there is no issue in my chat section all issues are from other part of app so i don't think you need flutter analyze for solve this issue.
```

### Flutter doctor output

```shell
[✓] Flutter (Channel stable, 2.10.2, on macOS 12.0.1 21A559 darwin-arm, locale en-IN)
    • Flutter version 2.10.2 at /Users/devduiux/StudioProjects/HubbleProject/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (3 weeks ago), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/devduiux/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.61.2)
    • VS Code at /Users/devduiux/Downloads/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • SM G965F (mobile) • 21f14474500d7ece • android-arm64  • Android 10 (API 29)
    • Chrome (web)
      • chrome           • web-javascript • Google Chrome 99.0.4844.51

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
Process finished with exit code 0
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by imtoori** [comment]
Hi 
I'm quite sure you need to specify the user associated with the reaction in your code 
```dart
bool isReacted = await getReactionResult(
message: controller.selectedQuotedMessage.value,
reaction: emoji.name.replaceAll(" ", ""));
if (isReacted) {
controller.channel.value.deleteReaction(
controller.selectedQuotedMessage.value,
Reaction(type: emoji.name.replaceAll(" ", ""),));
} else {
controller.channel.value.sendReaction(
controller.selectedQuotedMessage.value,
emoji.name.replaceAll(" ", "_"));
}```


Something like 
```dart
controller.channel.value.deleteReaction(
controller.selectedQuotedMessage.value,
Reaction(type: emoji.name.replaceAll(" ", ""), user: User(id: '<userid>')));
```
